name: Prueba deploy
on: 
    push:
        branches:
            - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18
      - name: Install packages
        run: npm install
      - name: Bundle
        run: npm run build