name: Prueba deploy
on: 
    push:
        branches:
            - main
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18
      - name: Install packages
        run: npm install
      - name: Bundle
        run: npm run build
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://prueba02-liard.vercel.app'
          docker_name: 'owasp/zap2docker-stable'
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Report
          path: owasp-zap-report.html          
          
          



